/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.8 Sun Jun 22 17:59:09 2025.
 */

#include <string.h>

#include "bps.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int bps_msgid_0_x406_pack(
    uint8_t *dst_p,
    const struct bps_msgid_0_x406_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_right_shift_u16(src_p->pack_voltage, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->pack_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->pack_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->pack_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->pack_soc, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->discharge_relay_status, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->charge_relay_status, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->charger_safety, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->charge_power_signal, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->balancing_active, 4u, 0x10u);

    return (6);
}

int bps_msgid_0_x406_unpack(
    struct bps_msgid_0_x406_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->pack_voltage = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->pack_voltage |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->pack_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->pack_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->pack_soc = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->discharge_relay_status = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->charge_relay_status = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->charger_safety = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->charge_power_signal = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->balancing_active = unpack_right_shift_u8(src_p[5], 4u, 0x10u);

    return (0);
}

int bps_msgid_0_x406_init(struct bps_msgid_0_x406_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bps_msgid_0_x406_t));

    return 0;
}

uint16_t bps_msgid_0_x406_pack_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double bps_msgid_0_x406_pack_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool bps_msgid_0_x406_pack_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bps_msgid_0_x406_pack_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double bps_msgid_0_x406_pack_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool bps_msgid_0_x406_pack_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_msgid_0_x406_pack_soc_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double bps_msgid_0_x406_pack_soc_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool bps_msgid_0_x406_pack_soc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_msgid_0_x406_discharge_relay_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x406_discharge_relay_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x406_discharge_relay_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x406_charge_relay_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x406_charge_relay_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x406_charge_relay_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x406_charger_safety_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x406_charger_safety_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x406_charger_safety_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x406_charge_power_signal_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x406_charge_power_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x406_charge_power_signal_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x406_balancing_active_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x406_balancing_active_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x406_balancing_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int bps_msgid_0_x106_pack(
    uint8_t *dst_p,
    const struct bps_msgid_0_x106_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->dtc_p0_a1_f_internal_cell_communication_fault, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->weak_cell_fault, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->low_cell_voltage_fault, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->cell_open_wiring_fault, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->current_sensor_fault, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->weak_pack_fault, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->thermistor_fault, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->can_communication_fault, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->redundant_power_supply_fault, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->high_voltage_isolation_fault, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->charge_enable_relay_fault, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->discharge_enable_relay_fault, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->internal_hardware_fault, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->dtc_p0_a0_a_internal_heatsink_thermistor_fault, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->internal_logic_fault, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->dtc_p0_a0_c_highest_cell_voltage_too_high_fault, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->dtc_p0_a0_e_lowest_cell_voltage_too_low_fault, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->pack_too_hot_fault, 2u, 0x04u);

    return (3);
}

int bps_msgid_0_x106_unpack(
    struct bps_msgid_0_x106_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->dtc_p0_a1_f_internal_cell_communication_fault = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->weak_cell_fault = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->low_cell_voltage_fault = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->cell_open_wiring_fault = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->current_sensor_fault = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->weak_pack_fault = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->thermistor_fault = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->can_communication_fault = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->redundant_power_supply_fault = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->high_voltage_isolation_fault = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->charge_enable_relay_fault = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->discharge_enable_relay_fault = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->internal_hardware_fault = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->dtc_p0_a0_a_internal_heatsink_thermistor_fault = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->internal_logic_fault = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->dtc_p0_a0_c_highest_cell_voltage_too_high_fault = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->dtc_p0_a0_e_lowest_cell_voltage_too_low_fault = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->pack_too_hot_fault = unpack_right_shift_u8(src_p[2], 2u, 0x04u);

    return (0);
}

int bps_msgid_0_x106_init(struct bps_msgid_0_x106_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bps_msgid_0_x106_t));

    return 0;
}

uint8_t bps_msgid_0_x106_dtc_p0_a1_f_internal_cell_communication_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_dtc_p0_a1_f_internal_cell_communication_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_dtc_p0_a1_f_internal_cell_communication_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_weak_cell_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_weak_cell_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_weak_cell_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_low_cell_voltage_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_low_cell_voltage_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_low_cell_voltage_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_cell_open_wiring_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_cell_open_wiring_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_cell_open_wiring_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_current_sensor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_current_sensor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_current_sensor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_weak_pack_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_weak_pack_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_weak_pack_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_thermistor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_thermistor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_thermistor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_can_communication_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_can_communication_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_can_communication_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_redundant_power_supply_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_redundant_power_supply_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_redundant_power_supply_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_high_voltage_isolation_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_high_voltage_isolation_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_high_voltage_isolation_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_charge_enable_relay_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_charge_enable_relay_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_charge_enable_relay_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_discharge_enable_relay_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_discharge_enable_relay_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_discharge_enable_relay_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_internal_hardware_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_internal_hardware_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_internal_hardware_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_dtc_p0_a0_a_internal_heatsink_thermistor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_dtc_p0_a0_a_internal_heatsink_thermistor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_dtc_p0_a0_a_internal_heatsink_thermistor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_internal_logic_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_internal_logic_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_internal_logic_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_dtc_p0_a0_c_highest_cell_voltage_too_high_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_dtc_p0_a0_c_highest_cell_voltage_too_high_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_dtc_p0_a0_c_highest_cell_voltage_too_high_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_dtc_p0_a0_e_lowest_cell_voltage_too_low_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_dtc_p0_a0_e_lowest_cell_voltage_too_low_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_dtc_p0_a0_e_lowest_cell_voltage_too_low_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_msgid_0_x106_pack_too_hot_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_msgid_0_x106_pack_too_hot_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_msgid_0_x106_pack_too_hot_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
