/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.8 Fri Apr 25 18:05:57 2025.
 */

 #include <string.h>

 #include "rivanna3.h"
 
 static inline uint8_t pack_left_shift_u8(
     uint8_t value,
     uint8_t shift,
     uint8_t mask)
 {
     return (uint8_t)((uint8_t)(value << shift) & mask);
 }
 
 static inline uint8_t pack_left_shift_u16(
     uint16_t value,
     uint8_t shift,
     uint8_t mask)
 {
     return (uint8_t)((uint8_t)(value << shift) & mask);
 }
 
 static inline uint8_t pack_right_shift_u16(
     uint16_t value,
     uint8_t shift,
     uint8_t mask)
 {
     return (uint8_t)((uint8_t)(value >> shift) & mask);
 }
 
 static inline uint16_t unpack_left_shift_u16(
     uint8_t value,
     uint8_t shift,
     uint8_t mask)
 {
     return (uint16_t)((uint16_t)(value & mask) << shift);
 }
 
 static inline uint8_t unpack_right_shift_u8(
     uint8_t value,
     uint8_t shift,
     uint8_t mask)
 {
     return (uint8_t)((uint8_t)(value & mask) >> shift);
 }
 
 static inline uint16_t unpack_right_shift_u16(
     uint8_t value,
     uint8_t shift,
     uint8_t mask)
 {
     return (uint16_t)((uint16_t)(value & mask) >> shift);
 }
 
 int rivanna3_aux_battery_status_pack(
     uint8_t *dst_p,
     const struct rivanna3_aux_battery_status_t *src_p,
     size_t size)
 {
     if (size < 3u) {
         return (-EINVAL);
     }
 
     memset(&dst_p[0], 0, 3);
 
     dst_p[0] |= pack_left_shift_u16(src_p->aux_voltage, 0u, 0xffu);
     dst_p[1] |= pack_right_shift_u16(src_p->aux_voltage, 8u, 0xffu);
     dst_p[2] |= pack_left_shift_u8(src_p->percent_full, 0u, 0xffu);
 
     return (3);
 }
 
 int rivanna3_aux_battery_status_unpack(
     struct rivanna3_aux_battery_status_t *dst_p,
     const uint8_t *src_p,
     size_t size)
 {
     if (size < 3u) {
         return (-EINVAL);
     }
 
     dst_p->aux_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
     dst_p->aux_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
     dst_p->percent_full = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
 
     return (0);
 }
 
 int rivanna3_aux_battery_status_init(struct rivanna3_aux_battery_status_t *msg_p)
 {
     if (msg_p == NULL) return -1;
 
     memset(msg_p, 0, sizeof(struct rivanna3_aux_battery_status_t));
 
     return 0;
 }
 
 uint16_t rivanna3_aux_battery_status_aux_voltage_encode(double value)
 {
     return (uint16_t)(value);
 }
 
 double rivanna3_aux_battery_status_aux_voltage_decode(uint16_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_aux_battery_status_aux_voltage_is_in_range(uint16_t value)
 {
     return (value <= 256u);
 }
 
 uint8_t rivanna3_aux_battery_status_percent_full_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_aux_battery_status_percent_full_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_aux_battery_status_percent_full_is_in_range(uint8_t value)
 {
     (void)value;
 
     return (true);
 }
 
 int rivanna3_motor_commands_pack(
     uint8_t *dst_p,
     const struct rivanna3_motor_commands_t *src_p,
     size_t size)
 {
     if (size < 8u) {
         return (-EINVAL);
     }
 
     memset(&dst_p[0], 0, 8);
 
     dst_p[0] |= pack_left_shift_u8(src_p->braking, 0u, 0x01u);
     dst_p[0] |= pack_left_shift_u8(src_p->regen_drive, 1u, 0x02u);
     dst_p[0] |= pack_left_shift_u8(src_p->manual_drive, 2u, 0x04u);
     dst_p[0] |= pack_left_shift_u8(src_p->cruise_drive, 3u, 0x08u);
     dst_p[0] |= pack_left_shift_u16(src_p->brake_pedal, 4u, 0xf0u);
     dst_p[1] |= pack_right_shift_u16(src_p->brake_pedal, 4u, 0x1fu);
     dst_p[1] |= pack_left_shift_u16(src_p->throttle, 5u, 0xe0u);
     dst_p[2] |= pack_right_shift_u16(src_p->throttle, 3u, 0x3fu);
     dst_p[2] |= pack_left_shift_u16(src_p->cruise_speed, 6u, 0xc0u);
     dst_p[3] |= pack_right_shift_u16(src_p->cruise_speed, 2u, 0x7fu);
     dst_p[3] |= pack_left_shift_u16(src_p->regen_braking, 7u, 0x80u);
     dst_p[4] |= pack_right_shift_u16(src_p->regen_braking, 1u, 0xffu);
     dst_p[5] |= pack_left_shift_u16(src_p->throttle_pedal, 0u, 0xffu);
     dst_p[6] |= pack_right_shift_u16(src_p->throttle_pedal, 8u, 0x01u);
 
     return (8);
 }
 
 int rivanna3_motor_commands_unpack(
     struct rivanna3_motor_commands_t *dst_p,
     const uint8_t *src_p,
     size_t size)
 {
     if (size < 8u) {
         return (-EINVAL);
     }
 
     dst_p->braking = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
     dst_p->regen_drive = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
     dst_p->manual_drive = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
     dst_p->cruise_drive = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
     dst_p->brake_pedal = unpack_right_shift_u16(src_p[0], 4u, 0xf0u);
     dst_p->brake_pedal |= unpack_left_shift_u16(src_p[1], 4u, 0x1fu);
     dst_p->throttle = unpack_right_shift_u16(src_p[1], 5u, 0xe0u);
     dst_p->throttle |= unpack_left_shift_u16(src_p[2], 3u, 0x3fu);
     dst_p->cruise_speed = unpack_right_shift_u16(src_p[2], 6u, 0xc0u);
     dst_p->cruise_speed |= unpack_left_shift_u16(src_p[3], 2u, 0x7fu);
     dst_p->regen_braking = unpack_right_shift_u16(src_p[3], 7u, 0x80u);
     dst_p->regen_braking |= unpack_left_shift_u16(src_p[4], 1u, 0xffu);
     dst_p->throttle_pedal = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
     dst_p->throttle_pedal |= unpack_left_shift_u16(src_p[6], 8u, 0x01u);
 
     return (0);
 }
 
 int rivanna3_motor_commands_init(struct rivanna3_motor_commands_t *msg_p)
 {
     if (msg_p == NULL) return -1;
 
     memset(msg_p, 0, sizeof(struct rivanna3_motor_commands_t));
 
     return 0;
 }
 
 uint8_t rivanna3_motor_commands_braking_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_motor_commands_braking_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_braking_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_motor_commands_regen_drive_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_motor_commands_regen_drive_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_regen_drive_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_motor_commands_manual_drive_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_motor_commands_manual_drive_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_manual_drive_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_motor_commands_cruise_drive_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_motor_commands_cruise_drive_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_cruise_drive_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint16_t rivanna3_motor_commands_brake_pedal_encode(double value)
 {
     return (uint16_t)(value);
 }
 
 double rivanna3_motor_commands_brake_pedal_decode(uint16_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_brake_pedal_is_in_range(uint16_t value)
 {
     return (value <= 256u);
 }
 
 uint16_t rivanna3_motor_commands_throttle_encode(double value)
 {
     return (uint16_t)(value);
 }
 
 double rivanna3_motor_commands_throttle_decode(uint16_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_throttle_is_in_range(uint16_t value)
 {
     return (value <= 256u);
 }
 
 uint16_t rivanna3_motor_commands_cruise_speed_encode(double value)
 {
     return (uint16_t)(value);
 }
 
 double rivanna3_motor_commands_cruise_speed_decode(uint16_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_cruise_speed_is_in_range(uint16_t value)
 {
     return (value <= 256u);
 }
 
 uint16_t rivanna3_motor_commands_regen_braking_encode(double value)
 {
     return (uint16_t)(value);
 }
 
 double rivanna3_motor_commands_regen_braking_decode(uint16_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_regen_braking_is_in_range(uint16_t value)
 {
     return (value <= 256u);
 }
 
 uint16_t rivanna3_motor_commands_throttle_pedal_encode(double value)
 {
     return (uint16_t)(value);
 }
 
 double rivanna3_motor_commands_throttle_pedal_decode(uint16_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_motor_commands_throttle_pedal_is_in_range(uint16_t value)
 {
     return (value <= 256u);
 }
 
 int rivanna3_dashboard_commands_pack(
     uint8_t *dst_p,
     const struct rivanna3_dashboard_commands_t *src_p,
     size_t size)
 {
     if (size < 1u) {
         return (-EINVAL);
     }
 
     memset(&dst_p[0], 0, 1);
 
     dst_p[0] |= pack_left_shift_u8(src_p->hazards, 0u, 0x01u);
     dst_p[0] |= pack_left_shift_u8(src_p->left_turn_signal, 1u, 0x02u);
     dst_p[0] |= pack_left_shift_u8(src_p->right_turn_signal, 2u, 0x04u);
     dst_p[0] |= pack_left_shift_u8(src_p->regen_en, 3u, 0x08u);
     dst_p[0] |= pack_left_shift_u8(src_p->cruise_inc, 4u, 0x10u);
     dst_p[0] |= pack_left_shift_u8(src_p->cruise_en, 5u, 0x20u);
     dst_p[0] |= pack_left_shift_u8(src_p->cruise_dec, 6u, 0x40u);
 
     return (1);
 }
 
 int rivanna3_dashboard_commands_unpack(
     struct rivanna3_dashboard_commands_t *dst_p,
     const uint8_t *src_p,
     size_t size)
 {
     if (size < 1u) {
         return (-EINVAL);
     }
 
     dst_p->hazards = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
     dst_p->left_turn_signal = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
     dst_p->right_turn_signal = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
     dst_p->regen_en = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
     dst_p->cruise_inc = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
     dst_p->cruise_en = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
     dst_p->cruise_dec = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
 
     return (0);
 }
 
 int rivanna3_dashboard_commands_init(struct rivanna3_dashboard_commands_t *msg_p)
 {
     if (msg_p == NULL) return -1;
 
     memset(msg_p, 0, sizeof(struct rivanna3_dashboard_commands_t));
 
     return 0;
 }
 
 uint8_t rivanna3_dashboard_commands_hazards_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_dashboard_commands_hazards_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_dashboard_commands_hazards_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_dashboard_commands_left_turn_signal_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_dashboard_commands_left_turn_signal_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_dashboard_commands_left_turn_signal_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_dashboard_commands_right_turn_signal_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_dashboard_commands_right_turn_signal_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_dashboard_commands_right_turn_signal_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_dashboard_commands_regen_en_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_dashboard_commands_regen_en_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_dashboard_commands_regen_en_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_dashboard_commands_cruise_inc_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_dashboard_commands_cruise_inc_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_dashboard_commands_cruise_inc_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_dashboard_commands_cruise_en_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_dashboard_commands_cruise_en_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_dashboard_commands_cruise_en_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_dashboard_commands_cruise_dec_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_dashboard_commands_cruise_dec_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_dashboard_commands_cruise_dec_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 int rivanna3_heartbeat_pack(
     uint8_t *dst_p,
     const struct rivanna3_heartbeat_t *src_p,
     size_t size)
 {
     if (size < 8u) {
         return (-EINVAL);
     }
 
     memset(&dst_p[0], 0, 8);
 
     dst_p[0] |= pack_left_shift_u8(src_p->from_wheel_board, 0u, 0x01u);
     dst_p[0] |= pack_left_shift_u8(src_p->from_power_board, 1u, 0x02u);
     dst_p[0] |= pack_left_shift_u8(src_p->from_telemetry_board, 2u, 0x04u);
 
     return (8);
 }
 
 int rivanna3_heartbeat_unpack(
     struct rivanna3_heartbeat_t *dst_p,
     const uint8_t *src_p,
     size_t size)
 {
     if (size < 8u) {
         return (-EINVAL);
     }
 
     dst_p->from_wheel_board = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
     dst_p->from_power_board = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
     dst_p->from_telemetry_board = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
 
     return (0);
 }
 
 int rivanna3_heartbeat_init(struct rivanna3_heartbeat_t *msg_p)
 {
     if (msg_p == NULL) return -1;
 
     memset(msg_p, 0, sizeof(struct rivanna3_heartbeat_t));
 
     return 0;
 }
 
 uint8_t rivanna3_heartbeat_from_wheel_board_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_heartbeat_from_wheel_board_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_heartbeat_from_wheel_board_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_heartbeat_from_power_board_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_heartbeat_from_power_board_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_heartbeat_from_power_board_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
 uint8_t rivanna3_heartbeat_from_telemetry_board_encode(double value)
 {
     return (uint8_t)(value);
 }
 
 double rivanna3_heartbeat_from_telemetry_board_decode(uint8_t value)
 {
     return ((double)value);
 }
 
 bool rivanna3_heartbeat_from_telemetry_board_is_in_range(uint8_t value)
 {
     return (value <= 1u);
 }
 
int rivanna3_charging_mode_pack(
    uint8_t *dst_p,
    const struct rivanna3_charging_mode_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->charging_mode_enable, 0u, 0x01u);

    return (1);
}

int rivanna3_charging_mode_unpack(
    struct rivanna3_charging_mode_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->charging_mode_enable = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int rivanna3_charging_mode_init(struct rivanna3_charging_mode_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_charging_mode_t));

    return 0;
}

uint8_t rivanna3_charging_mode_charging_mode_enable_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_charging_mode_charging_mode_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_charging_mode_charging_mode_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
